#ifndef VIPEROS_ECHIS_UTIL_DEBUG_H
#define VIPEROS_ECHIS_UTIL_DEBUG_H 1

#include <driver/debugcon.h>

#if defined(ECHIS_DEBUG_LOG_ALL)

#define ECHIS_PMM_DEBUG_LOG_ALLOC
#define ECHIS_PMM_DEBUG_LOG_FREE

#define ECHIS_HEAP_DEBUG_LOG_ALLOC
#define ECHIS_HEAP_DEBUG_LOG_FREE

#endif

#endif // VIPEROS_ECHIS_UTIL_DEBUG_H