#ifndef VIPEROS_ATHERIS_AMD64_UTIL_DEBUG_H
#define VIPEROS_ATHERIS_AMD64_UTIL_DEBUG_H 1

#if defined(ATHERIS_DEBUG_LOG_ALL)

//#define ATHERIS_VM_LOG_MAPPINGS

#endif

#endif // VIPEROS_ATHERIS_AMD64_UTIL_DEBUG_H